Repository annuaire-entreprises-data-gouv-fr/search-infra, pull requests merged in 2022-11, with the labels that each got.

#61 Ajout de nouvelles données - Colter, Elus, RGE, FINESS, UAI, CC, Entrepreneur Spectacle
  .gitignore
  DAG-insert-elk-sirene.py
  DAG-update-elk-colter-elu.py
  DAG-update-elk-convcollective.py
  DAG-update-elk-finess.py
  DAG-update-elk-rge.py
  DAG-update-elk-spectacle.py
  DAG-update-elk-uai.py
  data_aggregation/collectivite_territoriale.py
  data_aggregation/convention_collective.py
  data_aggregation/entrepreneur_spectacle.py
  data_aggregation/finess.py
  data_aggregation/rge.py
  data_aggregation/uai.py
  data_aggregation/update_elasticsearch.py
  elasticsearch/indexing_unite_legale.py
  elasticsearch/mapping_sirene_index.py
  helpers/utils.py
  task_functions.py
Labels: enhancement, new data

#68 Remove space from file path
  DAG-insert-elk-sirene.py
  data_aggregation/rge.py
Labels: bug

#69 fix: remove spaces from paths
  DAG-insert-elk-sirene.py
  DAG-update-elk-convcollective.py
  DAG-update-elk-rge.py
  data_aggregation/rge.py
Labels: bug

#71 fix: receive mattermost notif when data updated
  helpers/utils.py
Labels: bug, enhancement

#72 fix: lower case env names
  helpers/utils.py
Labels: bug

#73 fix: update enriched data on good index (next_color)
  DAG-insert-elk-sirene.py
Labels: bug

#75 fix: update schedule for update DAGs
  DAG-update-elk-colter-elu.py
  DAG-update-elk-convcollective.py
  DAG-update-elk-finess.py
  DAG-update-elk-rge.py
  DAG-update-elk-spectacle.py
  DAG-update-elk-uai.py
Labels: bug

#77 Ajouter liste des élus à l'index
  data_aggregation/collectivite_territoriale.py
  data_aggregation/update_elasticsearch.py
  elasticsearch/mapping_sirene_index.py
Labels: enhancement, new data
