Repository annuaire-entreprises-data-gouv-fr/search-infra, pull requests merged in 2023-03, with the labels that each got.

#115 Add cache flushing DAG
  .pre-commit-config.yaml
  DAG-flush-and-execute-queries.py
  DAG-flush-cache-only.py
  task_functions.py
Labels: enhancement, devops

#116 Refactor code and break down workflow functions
  DAG-change-api-color.py
  DAG-flush-and-execute-queries.py
  DAG-flush-cache-only.py
  DAG-insert-elk-sirene.py
  data_preprocessing/rge.py
  sqlite/queries/count_etabs_ouverts_query.py
  sqlite/queries/count_nombre_etabs.py
  sqlite/queries/count_nombre_etabs_ouverts.py
  sqlite/queries/create_table_colter.py
  sqlite/queries/create_table_convention_collective.py
  sqlite/queries/create_table_count_etabs.py
  sqlite/queries/create_table_count_etabs_ouverts.py
  sqlite/queries/create_table_dirigeant_pm.py
  sqlite/queries/create_table_dirigeant_pp.py
  sqlite/queries/create_table_elus.py
  sqlite/queries/create_table_etabs.py
  sqlite/queries/create_table_finess.py
  sqlite/queries/create_table_rge.py
  sqlite/queries/create_table_siret_siege.py
  sqlite/queries/create_table_spectacle.py
  sqlite/queries/create_table_uai.py
  sqlite/queries/create_table_unite_legale.py
  sqlite/queries/helpers.py
  sqlite/queries/populate_table_siret_siege.py
  sqlite/queries/select_dirigeants_pm_from_db.py
  sqlite/queries/select_dirigeants_pp_from_db.py
  sqlite/queries/select_fields_to_index.py
  sqlite/queries/select_sitemap_fields.py
  sqlite/sqlite_client.py
  task_functions.py
  task_functions/check_elastic_index.py
  task_functions/count_nombre_etablissements.py
  task_functions/count_nombre_etablissements_ouverts.py
  task_functions/create_additional_data_tables.py
  task_functions/create_and_fill_table_model.py
  task_functions/create_dirig_tables.py
  task_functions/create_elastic_index.py
  task_functions/create_etablissements_table.py
  task_functions/create_siege_only_table.py
  task_functions/create_sitemap.py
  task_functions/create_sqlite_database.py
  task_functions/create_unite_legale_table.py
  task_functions/execute_slow_elastic_queries.py
  task_functions/fill_elastic_siren_index.py
  task_functions/flush_cache.py
  task_functions/get_and_put_minio_object.py
  task_functions/get_colors.py
  task_functions/global_variables.py
  task_functions/slow_requests.py
  task_functions/update_color_file.py
  task_functions/update_sitemap.py
Labels: refactoring

#117 Ajout agence bio data + statut pour entrepreneur du spectacle
  DAG-insert-elk-sirene.py
  data_enrichment.py
  data_preprocessing/agence_bio.py
  data_preprocessing/entrepreneur_spectacle.py
  elasticsearch/mapping_sirene_index.py
  elasticsearch/process_unites_legales.py
  helpers/es_fields.py
  sqlite/queries/create_table_agence_bio.py
  sqlite/queries/create_table_spectacle.py
  sqlite/queries/select_fields_to_index.py
  task_functions/create_additional_data_tables.py
  task_functions/create_and_fill_table_model.py
  task_functions/get_and_put_minio_object.py
Labels: new data

#118 Ajout slug dans elasticsearch
  .pre-commit-config.yaml
  data_enrichment.py
  elasticsearch/mapping_sirene_index.py
  elasticsearch/process_unites_legales.py
  sqlite/queries/select_sitemap_fields.py
  task_functions/create_sitemap.py
Labels: enhancement, new data, refactoring

#137 feat: add flush cache task to main workflow
  DAG-insert-elk-sirene.py
Labels: enhancement

#138 Add API E2E tests to Airflow Workflow
  DAG-insert-elk-sirene.py
  tests/e2e_tests/run_tests.py
  tests/e2e_tests/test_api.py
Labels: enhancement

#140 feat: add slow queries with annuaire full requests
  task_functions/slow_requests.py
Labels: enhancement, performance

#139 feat: schedule workflow every monday, wednesday and friday at midnight
  DAG-insert-elk-sirene.py
Labels: performance
